# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-08 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('htmlLink', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('hangoutLink', models.CharField(blank=True, max_length=100, null=True)),
                ('is_allday', models.BooleanField()),
                ('recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone_origin', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creators', to='event.CreatorOrganizer')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizers', to='event.CreatorOrganizer')),
            ],
        ),
        migrations.RemoveField(
            model_name='show_event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='show_event',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Show_event',
        ),
    ]
